teams:
  1:
    name: "Red Team"
    spawnLocation:
      world: "world"
      x: 0
      y: 0
      z: 0
  2:
    name: "Blue Team"
    spawnLocation:
      world: "world"
      x: 0
      y: 0
      z: 0